#ifndef DEFINES_H
#define DEFINES_H

#include "secrets.h"
#include "logger.h"

#define WDT_TIMEOUT 3 // 3 seconds

#define CC1101_MOSI 23
#define CC1101_MISO 19
#define CC1101_SCLK 18
#define CC1101_CS 5
#define CC1101_GDO0 15

#define CC1101_RECEIVE_BUFFER_LENGTH 1024
#define CC1101_FORCE_FLUSH_DURATION 100000 // every 100ms (10 times per second)

#define WIFI_SSID SECRET_WIFI_SSID
#define WIFI_PASSWORD SECRET_WIFI_PASSWORD
#define WIFI_HOSTNAME "433mqtt"

#define WIFI_MAXIMUM_CONNECTION_TIME_BEFORE_REBOOT 10000 // 10 seconds

#define MQTT_KEEP_ALIVE 60 // 1 minute
#define MQTT_CONNECTION_ATTEMPT_INTERVAL 5000 // 5 seconds
#define MQTT_MAX_CONNECTION_ATTEMPTS_BEFORE_REBOOT 8
#define MQTT_BASE_TOPIC "433mqtt"

#define MQTT_SERVER "192.168.1.100"
#define MQTT_PORT 1883
#define MQTT_USERNAME SECRET_MQTT_USERNAME
#define MQTT_PASSWORD SECRET_MQTT_PASSWORD

#define HA_DEVICE_NAME "433MHZ Bridge"
#define HA_DEVICE_MODEL "ESP32 + CC1101"
#define HA_DEVICE_MANUFACTURER "Matrix"
#define HA_DEVICE_SW_VERSION "0.0.1"
#define HA_DEVICE_HW_VERSION "0.0.1"

#define PRINCETON_KEYS_MAXIMUM_COUNT 10

#define LOG_TAG_GLOBAL "433MHZ"
#define LOG_TAG_CC1101 "CC1101"
#define LOG_TAG_WIFI "WIFI"
#define LOG_TAG_MQTT "MQTT"
#define LOG_TAG_PRINCETON_KEYS "PrincetonKeys"
#define LOG_TAG_INFACTORY "Infactory"
#define LOG_TAG_PRINCETON "Princeton"

#endif //DEFINES_H
